def option4(Loaded_records):
    ''' This function helps us add a new customer. We can add details, where name is a required field.
    The new cusomer gets a unique autogenerated customer id. '''
    
    print("\nAdd new customer")
    
    while True:
        name = input("\nPlease enter customer's name*: ")
        if name != "":
            break
    postcode = input("Please enter customer's postcode: ")
    phone_number = input("Please enter customer's phone number: ")
    
    customer_data = Loaded_records.get("customer_records", {})
    customer_ids = []
    [customer_ids.append(int(key)) for key in customer_data.keys()]
        
    cust_id = 0
    for i in range(100000, 999999):
        if i not in customer_ids:
            cust_id = i
            break
    
    cust_id = str(cust_id)    
        
    new_customer = {
            'cust_id': cust_id,
            'name': name,
            'postcode': postcode,
            'phone number': phone_number
        }
    
    Loaded_records['customer_records'][cust_id] = new_customer
    
    print()
    
    for key, value in customer_data.items():
        if key == cust_id:
            print(key, value)
            break
    
    print("New customer added")
    return Loaded_records

loaded_records = {
    "customer_records": {
        "100000": {"cust_id": "100000", "name": "Christine Salt", "postcode": "6180", "phone number": "043908827"},
        "100001": {"cust_id": "100001", "name": "Brian Dombrowski", "postcode": "6132", "phone number": "048531388"},
        "100002": {"cust_id": "100002", "name": "Alan Manlio", "postcode": "6132", "phone number": "041949472"}
    },
    "sales_records": {
        "100000000": {"date": "2020-01-01", "customer_id": "100001", "category": "computer equipment", "value": 1144.16},
        "100000001": {"date": "2020-03-02", "customer_id": "100002", "category": "furniture", "value": 930.29},
        "100000002": {"date": "2020-01-03", "customer_id": "100002", "category": "household appliances", "value": 4520.66},
        "100000006": {"date": "2020-01-03", "customer_id": "100002", "category": "household appliances", "value": 4520.66},
        "100000007": {"date": "2020-04-03", "customer_id": "100002", "category": "alcohol and beverage", "value": 3577.84},
        "100000004": {"date": "2020-04-03", "customer_id": "100002", "category": "alcohol and beverage", "value": 3577.84},
        "100000011": {"date": "2020-04-03", "customer_id": "100002", "category": "alcohol and beverage", "value": 3577.84}
    }
}

option4(loaded_records)
print(loaded_records)